### ISSUE TITLE
Add support for python applications

### ISSUE THREAD

**Issue by aliartiza75** [stakater/stakater-pipeline-library#54]
Need to add support for python applications.

**Comment by rasheedamir** [comment]
@aliartiza75 making a PR soon?

**Comment by aliartiza75** [comment]
@rasheedamir yes sir :)

**Comment by aliartiza75** [comment]
python support has been added

https://github.com/stakater/stakater-pipeline-library/pull/71

**Comment by aliartiza75** [comment]
@rasheedamir @ahmedwaleedmalik closing this issue, PR has been merged.
